language: c++
os: linux
sudo: false

env:
  matrix:
    - TRAVIS_NO_EMPTY_JOB=true

matrix:
  exclude:
    - env: TRAVIS_NO_EMPTY_JOB=true

  include:
    - env: COMPILER=clang++-3.6
      addons: &clang36
        apt:
          packages:
            - clang-3.6
            - cmake
            - g++-5
            - libboost-test-dev
            - mesa-common-dev
            - libgl1-mesa-dev
            - libegl1-mesa-dev
            - libglew-dev
            - libglfw-dev
            - libopenal-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - ./configure.py --build-dir _build --cmake -DCMAKE_CXX_COMPILER=${COMPILER}
  - cmake --build _build

script:
  - cd ${TRAVIS_BUILD_DIR}/_build/test
  - ctest

notifications:
  email: false
